export const en = {
  // Header
  appName: "Resonance AI",
  appDescription: "Music search that understands context. Describe a mood, sound color, scale, or a movie scene. The play button will take you to the song's page on Spotify.",
  
  // Input
  placeholder: "For example: I need music for a night drive in the rain, something in noir-jazz style, but with modern bass...",
  aiAnalyzes: "AI analyzes context",
  searchButton: "Find resonance",
  searching: "Searching...",
  
  // Error
  errorMessage: "Failed to get recommendations. Try rephrasing or check your API key.",
  
  // Results
  requestAnalysis: "Request Analysis",
  recommendationsGenerated: "Recommendations generated by Gemini 2.5 Flash. Music parameters are estimates.",
  
  // Song Card
  listenOnSpotify: "Listen on Spotify",
  checkKey: "Check key signature",
  checkBpm: "Check BPM",
  showSpectrum: "Show spectrum",
  hideAnalysis: "Hide analysis",
  audioProfile: "Audio Profile",
  
  // Vibe Visualizer
  energy: "Energy",
  mood: "Mood",
  acousticness: "Acousticness",
  danceability: "Danceability",
  complexity: "Complexity",
  
  // Vibe Tags
  melancholic: "Melancholic",
  aggressive: "Aggressive",
  dreamy: "Dreamy",
  nostalgic: "Nostalgic",
  cyberpunk: "Cyberpunk",
  lofi: "Lo-Fi",
  jazzy: "Jazzy",
  dark: "Dark",
  euphoric: "Euphoric",
  
  // Language selector
  language: "Language",
  english: "English",
  russian: "Russian",
  romanian: "Romanian",
};
